site_name: GenGen wiki
site_author: GGenerals
site_url: https://gengen.qzz.io/wiki/

theme:
  name: material

  palette:
    # 亮色模式
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式

    # 暗色模式
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

  features:
    - navigation.tabs
    - content.tabs.link

  language: zh

extra_css:
  - css/theme.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros

markdown_extensions:
  - admonition

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys

nav:
  - 首页: index.md

  - 数据结构:
      - 线段树:
          - 线段树基础: data_structure/线段树/Segment_basic.md
      - 分块:
          - 倍增值域分块: data_structure/分块/倍增值域分块.md

  - 数学:
      - 数学基础:
          - 集合与逻辑: math/数学基础/set_logic.md
          - 函数入门: math/数学基础/function.md
          - 复数: math/数学基础/complex.md
          - 向量入门: math/数学基础/vector.md

      - 数论:
          - 数论基础: math/数论/mod-prime.md
          - 中国剩余定理: math/数论/crt.md
          - 最大公因数: math/数论/gcd.md

      - 生成函数:
          - 普通型生成函数: math/生成函数/ogf.md
          - 指数型生成函数: math/生成函数/egf.md

  - 字符串:
      - 字典树: string/Trie.md