site_name: GenGen wiki
site_author: GGenerals
site_url: https://gengen.qzz.io/wiki/

theme:
  name: material
  custom_dir: overrides 

  features:
    # --- 代码块增强 ---
    - content.code.copy          # 为代码块启用复制按钮[reference:2]
    - content.code.annotate      # 为代码块启用注解功能（可选）

    # --- 内容选项卡增强 ---
    - content.tabs.link          # 允许内容选项卡的链接联动[reference:3]
    - content.tooltips          # 启用改进的提示气泡

  palette:
    # 亮色模式
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式

    # 暗色模式
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

  features:
    - navigation.tabs
    - content.tabs.link

  language: zh

extra_css:
  - css/theme.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros

markdown_extensions:
  - admonition

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true

  - admonition                  # 提示框基础
  - pymdownx.details            # 可折叠提示框
  - pymdownx.tabbed:
      alternate_style: true     # 内容标签页 (必需)
  - pymdownx.superfences        # 标签页嵌套内容、代码注解的基础
  - attr_list                   # 按钮、注解所需的属性列表
  - md_in_html                  # 注解在HTML中的支持
  - tables                      # 数据表格
  # 以下为可选但建议启用的项
  - pymdownx.highlight:
      anchor_linenums: true     # 代码块行号锚点
  - toc:
      permalink: true           # 标题永久链接
  

nav:
  - 首页: 
    - 介绍: index.md
    - 快速开始: quickstart.md

  - 图论:
      - 最短路:
          - 单源最短路算法: graph/最短路/单源最短路算法.md
          - 多源最短路算法: graph/最短路/多源最短路算法.md
          - 最短路应用: graph/最短路/最短路应用.md
      - 最小生成树:
          - 最小生成树算法: graph/最小生成树/最小生成树算法.md
          - 最小生成树应用: graph/最小生成树/最小生成树应用.md
  - 数据结构:
      - 线段树:
          - 线段树基础: data_structure/线段树/Segment_basic.md
      - 平衡树:
          - 平衡树基础: data_structure/平衡树/Balanced_tree_basic.md
          - Splay: data_structure/平衡树/Splay.md
          - FHQ-Treap: data_structure/平衡树/FHQ-Treap.md
      - 分块:
          - 倍增值域分块: data_structure/分块/倍增值域分块.md
      - 可持久化:
          - 可持久化基础: data_structure/可持久化/Persistent_Data_Structure.md

  - 数学:
      - 数学基础:
          - 集合与逻辑: math/数学基础/set_logic.md
          - 函数入门: math/数学基础/function.md
          - 复数: math/数学基础/complex.md
          - 向量入门: math/数学基础/vector.md

      - 数论:
          - 数论基础: math/数论/mod-prime.md
          - 最大公因数: math/数论/gcd.md
          - 模意义下的乘法逆元: math/数论/Inverse_element.md
          - 中国剩余定理: math/数论/crt.md

      - 生成函数:
          - 普通型生成函数: math/生成函数/ogf.md
          - 指数型生成函数: math/生成函数/egf.md

  - 字符串:
      - 字典树: string/Trie.md